#!/bin/bash



. /etc/rc.d/functions

PROC=nvgred
PREFIX=/usr/local/bin
CLIENT=${PREFIX}/nvconfig
SERVER=${PREFIX}/${PROC}
PID_FILE=/var/run/${PROC}.pid



if [ ! -x ${SERVER} ]; then
	SERVER=`which nvgred`
fi

if [ ! -x ${CLIENT} ]; then
	CLIENT=`which nvgred`
fi



start_func() {

	echo -n "Starting ${PROC}:"

	if [ -f ${PID_FILE} ]; then
		failure
		echo
		echo "Already running, PID: `cat ${PID_FILE}`"
		exit 1
	fi

	${SERVER} -d && success || failure
	if [ -f ${PID_FILE} ]; then
		echo "Started: `cat ${PID_FILE}`"
	else
		echo "Cannot start nvgred"
	fi
}



stop_func() {

	echo -n "Stopping ${PROC}:"

	if [ -f ${PID_FILE} ]; then
		killproc ${PROC} && success || failure
		rm -f ${PID_FILE} > /dev/null 2>&1
		echo
	else
		failure
		echo
		echo "${PROC} is not running"
	fi
}



status_func() {

	if [ -f ${PID_FILE} ]; then
		echo "Running, PID: `cat ${PID_FILE}`"
	else
		echo "${PROC} is not running"
	fi
}



case "$1" in
	start)
		start_func
	;;
	restart)
		stop_func
		start_func
	;;
	status)
		status_func
	;;
	stop)
		stop_func
	;;
	*)
		echo "Usage: /etc/init.d/nvgred {start|stop|status}"
	;;
esac

exit 0
