#!/bin/bash



PREFIX=/usr/local/bin
CLIENT=${PREFIX}/nvconfig
SERVER=${PREFIX}/nvgred
PID_FILE=/var/run/nvgred.pid



if [ ! -x ${SERVER} ]; then
	SERVER=`which nvgred`
fi

if [ ! -x ${CLIENT} ]; then
	CLIENT=`which nvgred`
fi



start_func() {

	if [ -f ${PID_FILE} ]; then
		echo "Already running, PID: `cat ${PID_FILE}`"
		exit 1
	fi

	${SERVER} -d
	if [ -f ${PID_FILE} ]; then
		echo "Started: `cat ${PID_FILE}`"
	else
		echo "Cannot start nvgred"
	fi
}



stop_func() {

	if [ -f ${PID_FILE} ]; then
		kill `cat ${PID_FILE}` > /dev/null 2>&1
		rm -f ${PID_FILE} > /dev/null 2>&1
	fi

	echo "Stopped"
}



status_func() {

	if [ -f ${PID_FILE} ]; then
		echo "Running, PID: `cat ${PID_FILE}`"
	else
		echo "Stopping"
	fi
}



case "$1" in
	start)
		start_func
	;;
	restart)
		stop_func
		start_func
	;;
	status)
		status_func
	;;
	stop)
		stop_func
	;;
	*)
		echo "Usage: /etc/init.d/nvgred {start|stop|status|restart}"
	;;
esac

exit 0
